#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_CAMERA_GC0301)		+= prize_dual_camera/
obj-$(CONFIG_PRIZE_FM)		+= fm_ant/
obj-$(CONFIG_PRIZE_AW2016A)		+= aw2016a/
obj-$(CONFIG_LEDS_AW210XX)		+= AW210XX/
obj-$(CONFIG_LEDS_AW22127)		+= aw22127/
obj-$(CONFIG_PRIZE_HARDWARE_INFO)		+= hardware_info/
obj-$(CONFIG_PRIZE_EXERGEN)		+= prize_exergen/
obj-$(CONFIG_PRIZE_ENDOSCOPE) += endoscope/
#prize add by wangfei for motor aw86927 20221021 start
obj-$(CONFIG_AWINIC_HAPTIC_HV) += haptic_hv/
#prize add by wangfei for motor aw86927 20221021 end
#drv add by situziyin 20230309 start
obj-$(CONFIG_PRIZE_PIXEL_MANAGER) += pixel_manager/
#drv added by wangwei1, secondary screen driver, 20230606-start
obj-$(CONFIG_PRIZE_LCD_GC9A01) += lcd_gc9a01/
obj-$(CONFIG_PRIZE_LCD_GC9A01_240) += lcd_gc9a01_240/
#drv added by wangwei1, secondary screen driver, 20230606-end
#drv add by situziyin 20230309 end
#prize add by xuejian for gesture 20230210 start
obj-$(CONFIG_PRIZE_COMMON_NODE) += prize_common_node/
#prize add by xuejian for gesture 20230210 end
#drv add by wmd 20230529,add digital lcd,start
obj-$(CONFIG_PRIZE_DIGITAL_LCD) += dlcd/
#drv add by wmd 20230529,add digital lcd,end 
#drv add by liuxuhui for sensor hall start --- 20231123
obj-$(CONFIG_PRIZE_HALL) += hall/
#drv add by liuxuhui for sensor hall end --- 20231123
#drv add by yaozhipeng for sensor 3d hall start --- 20240130
obj-$(CONFIG_3D_HALL_IST8309) += hall_ist8309/
#drv add by yaozhipeng for sensor 3d hall end --- 20240130
#drv added by chenjiaxi, add miniscreen driver, start
obj-$(CONFIG_DRV_MINISCREEN) += miniscreen/
#drv added by chenjiaxi, add miniscreen driver, end
