KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)

$(info [fm_drv:Kbuild] CFG_LEGACY_BUILD = $(CFG_LEGACY_BUILD))
$(info [fm_drv:Kbuild] KO_CODE_PATH = $(KO_CODE_PATH))

ifneq ($(CFG_LEGACY_BUILD), yes)
obj-m += Build/connac2x/
obj-m += Build/mt6625/
obj-m += Build/mt6627/
obj-m += Build/mt6630/
obj-m += Build/mt6631/
obj-m += Build/mt6631_6635/
#obj-m += Build/mt6632/
obj-m += Build/mt6635/
obj-m += Build/soc/
else
include $(KO_CODE_PATH)/Kbuild.include
endif
