#for AWINIC AW87XXX Smart K PA
#obj-$(CONFIG_SND_SOC_AW87XXX) += aw87xxx.o aw_device.o aw_monitor.o aw_bin_parse.o aw_dsp.o aw_acf_bin.o
obj-m += aw87xxx_pa.o
aw87xxx_pa-y	+= aw87xxx.o
aw87xxx_pa-y	+= aw87xxx_device.o
aw87xxx_pa-y	+= aw87xxx_monitor.o
aw87xxx_pa-y	+= aw87xxx_bin_parse.o
aw87xxx_pa-y	+= aw87xxx_dsp.o
aw87xxx_pa-y	+= aw87xxx_acf_bin.o