#
# Makefile for the show hardware info drivers.
#
##include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/pwm/pwm_v1/include/
obj-m :=  dlcd.o
