#
# Makefile for TMS devices
#

obj-$(CONFIG_TMS_DEVICE)     += tms_common_module.o
tms_common_module-objs       := tms_common.o
obj-$(CONFIG_TMS_NFC_DEVICE) += nfc/
obj-$(CONFIG_TMS_ESE_DEVICE) += ese/
